import { ImageResponse } from "next/og";

export const alt = "Umesh Mavadiya — Full-Stack Developer. Thoughtful engineering. Reliable digital products.";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpenGraphImage() {
  return new ImageResponse(<div style={{ width: "100%", height: "100%", display: "flex", flexDirection: "column", background: "#f8f7f4", padding: "56px 65px", color: "#242722", fontFamily: "sans-serif" }}><div style={{ display: "flex", alignItems: "center", gap: 13 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "center", width: 43, height: 43, background: "#242722", color: "#fff", borderRadius: 9, fontSize: 22, letterSpacing: -3 }}>um.</div><span style={{ fontSize: 22, fontWeight: 600 }}>Umesh Mavadiya</span><span style={{ marginLeft: "auto", fontSize: 13, color: "#6a7960" }}>FULL-STACK DEVELOPER</span></div><div style={{ display: "flex", flex: 1, alignItems: "center", justifyContent: "space-between", gap: 35 }}><div style={{ display: "flex", flexDirection: "column", fontSize: 66, letterSpacing: -3, lineHeight: 1.13, fontWeight: 700 }}><span>I build scalable,</span><span style={{ color: "#d85e35" }}>high-performance</span><span>web applications.</span></div><div style={{ display: "flex", flexDirection: "column", background: "#242c25", width: 315, borderRadius: 13, padding: 26, gap: 22, transform: "rotate(-4deg)", color: "#c3d0b1", border: "1px solid #68745c" }}><span style={{ fontSize: 13, color: "#b79874" }}>idea → production</span>{["01   React / Next.js", "02   Node.js / REST APIs", "03   MongoDB / SQL", "04   AWS / Azure"].map((item) => <span key={item} style={{ fontSize: 18, borderTop: "1px solid #46513e", paddingTop: 16 }}>{item}</span>)}</div></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: 23, borderTop: "1px solid #d9ddcf", fontSize: 15, color: "#7c876f" }}><span>5+ years of professional experience</span><span>Thoughtful engineering. Reliable products.</span><span style={{ color: "#bf653c" }}>Let’s build something good. ↗</span></div></div>, size);
}
