"use client";

import { useState } from "react";
import { ArrowUpRight, Braces, Check, CheckCheck, Circle, Cloud, Database, GitBranch, Sparkles, Terminal } from "lucide-react";
import { TechnologyMark } from "@/components/ui";

const scenes = [
  { id: "frontend", label: "Frontend", technology: "React / Next.js", file: "app.config.ts", lines: ["// Great products start with a solid foundation.", "", "const application = {", "  frontend: ['React', 'Next.js'],", "  backend: 'Node.js',", "  database: ['MongoDB', 'SQL'],", "  cloud: ['AWS', 'Azure'],", "  builtWith: 'Purpose & precision',", "};", "", "export default bringToLife(application);"] },
  { id: "backend", label: "Backend", technology: "Node.js / APIs", file: "api/router.ts", lines: ["// Clear contracts. Reliable foundations.", "", "const api = createRouter({", "  runtime: 'Node.js',", "  authentication: true,", "  validation: 'Every request',", "  authorization: 'Every resource',", "  errors: 'Handled with care',", "});", "", "export default api;"] },
  { id: "database", label: "Database", technology: "MongoDB / SQL", file: "data/schema.ts", lines: ["// Good architecture begins with good data.", "", "const persistence = {", "  models: 'Thoughtfully structured',", "  queries: 'Purposefully indexed',", "  integrity: 'Always enforced',", "  migrations: 'Version controlled',", "  access: 'Least privilege',", "};", "", "export default persistence;"] },
  { id: "cloud", label: "Cloud", technology: "AWS / Azure", file: "deploy.config.ts", lines: ["// From a local commit to a live product.", "", "const pipeline = {", "  source: 'Git',", "  steps: ['Build', 'Test', 'Deploy'],", "  environment: 'Reproducible',", "  secrets: 'Never in the code',", "  release: 'Production ready',", "};", "", "export default pipeline;"] },
];

function Highlight({ text }: { text: string }) {
  if (text.startsWith("//")) return <span className="code-comment">{text}</span>;
  return <>{text.split(/('[^']*'|\b(?:const|export|default|true)\b)/g).map((part, index) => <span key={index} className={part.startsWith("'") ? "code-string" : /^(const|export|default|true)$/.test(part) ? "code-keyword" : undefined}>{part}</span>)}</>;
}

export function HeroScene() {
  const [active, setActive] = useState(0);
  const scene = scenes[active];
  return <div className="hero-scene" aria-label="Explore the layers of a full-stack application"><div className="scene-grid" aria-hidden="true" /><div className="scene-orbit orbit-one" aria-hidden="true" /><div className="scene-orbit orbit-two" aria-hidden="true" /><div className="scene-caption"><span className="little-cross">+</span> GOOD IDEAS. SOLID ENGINEERING.</div><div className="idea-label"><Sparkles size={13} /> idea → production</div><div className="editor-backplate" aria-hidden="true" /><div className="code-editor"><div className="editor-titlebar"><div className="window-dots" aria-hidden="true"><i /><i /><i /></div><span><Braces size={13} /> {scene.file}</span><span className="editor-language">TS</span></div><div className="editor-code" aria-live="polite" aria-atomic="true"><code>{scene.lines.map((line, index) => <span className="code-line" key={`${scene.id}-${index}`}><span className="line-number" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><span><Highlight text={line} /></span></span>)}</code></div><div className="editor-status"><span><GitBranch size={12} /> main <CheckCheck size={12} /></span><span><Circle size={6} fill="currentColor" /> All checks passed</span><span>UTF-8</span></div></div><div className="floating-code-mark" aria-hidden="true"><Braces size={30} /><span>clean code.</span></div><div className="deployment-card"><div className="deployment-icon"><Check size={20} strokeWidth={2.5} /></div><div><strong>Ready for the real world.</strong><span>Scalable. Reliable. Production-ready.</span></div><ArrowUpRight size={15} /></div><svg className="scene-connectors" viewBox="0 0 520 470" fill="none" preserveAspectRatio="none" aria-hidden="true"><path d="M260 320V365M65 365H455M65 365V393M195 365V393M325 365V393M455 365V393" stroke="currentColor" strokeWidth="1" strokeDasharray="4 4" /><circle cx="260" cy="350" r="4" fill="var(--accent)" stroke="var(--background)" strokeWidth="3" /></svg><div className="scene-stack" aria-label="Application layers">{scenes.map((item, index) => <button key={item.id} onClick={() => setActive(index)} className={`stack-node ${index === active ? "stack-node-active" : ""}`} aria-pressed={index === active} aria-label={`Explore ${item.label}`}><span className={`stack-icon ${item.id}`}>{index === 0 ? <TechnologyMark name="React" size={20} /> : index === 1 ? <TechnologyMark name="Node.js" size={20} /> : index === 2 ? <Database size={19} /> : <Cloud size={20} />}</span><strong>{item.label}</strong><span>{item.technology}</span></button>)}</div><div className="scene-bottom"><Terminal size={11} /><span>ENGINEERED TO WORK. BUILT TO LAST.</span><span className="little-cross">+</span></div></div>;
}
