import { Activity, ArrowUpRight, AudioLines, Bell, Check, ChevronDown, Circle, Command, FileText, Folder, Grid2X2, Headphones, LayoutDashboard, ListTodo, Mic, MoreHorizontal, Plus, Radio, Search, Settings, Shield, ShoppingBag, SlidersHorizontal, Sparkles, Users, Zap } from "lucide-react";
import type { Project } from "@/data/projects";

function MiniChart({ color = "#9387d8" }: { color?: string }) {
  return <svg className="mini-chart" viewBox="0 0 280 78" preserveAspectRatio="none" fill="none"><path d="M0 20H280M0 45H280M0 70H280" stroke="#eae9ef" strokeDasharray="3 3" /><path d="M0 61C20 60 18 46 38 49S64 64 84 36S109 50 130 30S157 45 180 19S211 29 230 13S260 22 280 3V78H0Z" fill={color} opacity=".1" /><path d="M0 61C20 60 18 46 38 49S64 64 84 36S109 50 130 30S157 45 180 19S211 29 230 13S260 22 280 3" stroke={color} strokeWidth="2" /></svg>;
}

function MiniSidebar({ dark = false, name = "workspace" }: { dark?: boolean; name?: string }) {
  return <div className={`mini-sidebar ${dark ? "mini-sidebar-dark" : ""}`}><div className="mini-brand"><Command size={15} /><b>{name}</b></div><span className="mini-sidebar-label">WORKSPACE</span>{[{ icon: LayoutDashboard, name: "Overview" }, { icon: Folder, name: "Projects" }, { icon: FileText, name: "Reports" }, { icon: Users, name: "Team" }, { icon: Activity, name: "Activity" }].map(({ icon: Icon, name: item }, i) => <div key={item} className={`mini-nav ${i === 0 ? "mini-nav-active" : ""}`}><Icon size={10} />{item}</div>)}<div className="mini-sidebar-bottom"><Settings size={11} /> Settings<span className="mini-avatar">U</span></div></div>;
}

function ReportingPreview() {
  return <div className="mini-app reporting-app"><MiniSidebar dark name="reports" /><div className="mini-main"><div className="mini-toolbar"><span>Workspace <span>/</span> Overview</span><div><Search size={10} /><Bell size={10} /><span className="mini-avatar">U</span></div></div><div className="mini-page-title"><div><h4>Reporting overview</h4><p>A clearer view of your reporting workflow.</p></div><span className="mini-primary"><Plus size={9} /> New report</span></div><div className="report-summary">{[{ text: "Ready for review", icon: FileText, color: "violet" }, { text: "Approved reports", icon: Check, color: "green" }, { text: "Saved drafts", icon: Folder, color: "amber" }].map(({ text, icon: Icon, color }) => <div key={text}><span className={`mini-stat-icon ${color}`}><Icon size={12} /></span><span>{text}<b>{text.startsWith("Ready") ? "In review" : text.startsWith("Approved") ? "Up to date" : "Auto-saved"}</b></span><ArrowUpRight size={10} /></div>)}</div><div className="report-charts"><div className="mini-panel"><div className="mini-panel-title">Reporting activity<span>This week <ChevronDown size={8} /></span></div><MiniChart /><div className="chart-days"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="mini-panel donut-panel"><div className="mini-panel-title">By status<MoreHorizontal size={10} /></div><div className="mini-donut"><span><Check size={16} /></span></div><div className="mini-legend"><i />Approved<i />In review</div></div></div><div className="mini-table-title">Recent reports <span>View all <ArrowUpRight size={8} /></span></div><div className="mini-table-row header"><span>REPORT NAME</span><span>OWNER</span><span>STATUS</span></div>{["Operational overview", "Project health report", "Monthly review"].map((report, i) => <div className="mini-table-row" key={report}><span><FileText size={10} />{report}</span><span className="mini-person"><i />Team</span><span className={`mini-status ${i === 1 ? "status-amber" : ""}`}>{i === 1 ? "In review" : "Approved"}</span></div>)}</div></div>;
}

function BusinessPreview() {
  return <div className="mini-app business-app"><MiniSidebar name="workspace" /><div className="mini-main"><div className="mini-toolbar"><span><Grid2X2 size={10} /> Your workspace</span><div><Search size={10} /><Bell size={10} /><span className="mini-avatar">U</span></div></div><div className="mini-page-title"><div><h4>Everything, in one place.</h4><p>Your team’s work, moving forward.</p></div><span className="mini-primary"><Plus size={9} /> Add project</span></div><div className="business-stats"><div><span><Folder size={11} />Projects</span><strong>Moving forward <ArrowUpRight size={12} /></strong><i /></div><div><span><ListTodo size={11} />Team tasks</span><strong>On track <Check size={12} /></strong><i /></div><div><span><Users size={11} />Collaboration</span><strong>Better together <Users size={12} /></strong><i /></div></div><div className="business-content"><div className="mini-panel"><div className="mini-panel-title">Project activity<span>Weekly <ChevronDown size={8} /></span></div><div className="mini-bars">{[35, 57, 42, 74, 53, 85, 65, 95, 73, 89, 66, 82].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-days"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span></div></div><div className="mini-panel team-tasks"><div className="mini-panel-title">Today’s focus<MoreHorizontal size={10} /></div>{["Review application flow", "Update API integration", "Prepare next release"].map((task, i) => <div key={task}><span className={`mini-checkbox ${i === 0 ? "checked" : ""}`}>{i === 0 && <Check size={7} />}</span><span>{task}<small>{i === 0 ? "Completed" : "In progress"}</small></span></div>)}</div></div><div className="mini-table-title">Active projects <span>View board <ArrowUpRight size={8} /></span></div>{["Platform development", "Customer experience"].map((item, i) => <div className="business-project-row" key={item}><span className={`project-tile tile-${i}`}><Folder size={11} /></span><span>{item}<small>Product team</small></span><div className="mini-avatars"><i>A</i><i>M</i><i>R</i></div><span className="mini-status">In progress</span></div>)}</div></div>;
}

function NotificationPreview() {
  return <div className="notification-app"><div className="notification-top"><span><Bell size={15} /> Inbox</span><span className="live-pill"><i /> Live updates</span><MoreHorizontal size={14} /></div><div className="notification-head"><h4>You’re in the loop.</h4><p>Everything that matters, right here.</p></div><div className="notification-tabs"><span className="selected">All updates</span><span>Unread</span><span>Archived</span><span><Check size={10} /> Mark all read</span></div>{[{ icon: Folder, title: "Your project is moving forward", desc: "A new milestone is ready for your review.", time: "Just now", color: "violet" }, { icon: Users, title: "A better way to work together", desc: "You’ve been invited to the product workspace.", time: "Recently", color: "green" }, { icon: Shield, title: "Your account, protected", desc: "Your security preferences are up to date.", time: "Earlier", color: "amber" }].map(({ icon: Icon, title, desc, time, color }, i) => <div className={`notification-row ${i === 0 ? "notification-unread" : ""}`} key={title}><div className={`notification-icon ${color}`}><Icon size={16} /></div><div><strong>{title}</strong><p>{desc}</p><span>{time}</span></div>{i === 0 && <i className="unread-dot" />}</div>)}<div className="notification-footer"><Zap size={10} /> Connected. Synced. Up to date.</div></div>;
}

function VoicePreview() {
  return <div className="voice-app"><div className="voice-top"><span><AudioLines size={17} /> voice<span className="voice-wordmark-dot">.</span></span><span><i /> SESSION PREVIEW</span><SlidersHorizontal size={14} /></div><div className="voice-center"><div className="voice-orb"><AudioLines size={28} strokeWidth={1.3} /></div><h4>A little more human.</h4><p>Your ideas. A natural conversation.</p><div className="voice-wave">{Array.from({ length: 45 }, (_, i) => <i key={i} style={{ height: `${8 + Math.abs(Math.sin(i * 2.3)) * (33 - Math.abs(i - 22))}px` }} />)}</div><span className="voice-transcript">“Let’s turn that idea into a plan.”</span><div className="voice-controls"><span><Headphones size={12} /></span><span className="voice-mic"><Mic size={17} /></span><span><Settings size={12} /></span></div></div><div className="voice-bottom"><span><Shield size={10} /> Designed with privacy in mind</span><span>Speech → Intelligence → Action <ArrowUpRight size={10} /></span></div></div>;
}

function CommercePreview() {
  return <div className="commerce-app"><div className="commerce-nav"><strong>everyday<span>.</span></strong><span>Objects with purpose.</span><ShoppingBag size={14} /></div><div className="commerce-hero"><div><span>CONSIDERED ESSENTIALS</span><h4>Less, but<br />better.</h4><p>Thoughtfully made for everyday living.</p><span className="commerce-link">Explore the collection <ArrowUpRight size={11} /></span></div><div className="product-object"><div className="product-arch" /><div className="product-cylinder" /><div className="product-shadow" /></div></div><div className="commerce-bottom"><span>Timeless design.</span><span>Made to be used.</span><span>Built to stay.</span></div></div>;
}

function IotPreview() {
  return <div className="iot-app"><div className="iot-top"><span><Radio size={15} /> Connected systems</span><span><i /> DEVICE PREVIEW</span></div><div className="iot-title"><div><h4>A clearer signal.</h4><p>Your devices. One connected view.</p></div><span><Activity size={13} /> Live telemetry</span></div><div className="iot-gauges">{["Environment", "Connectivity", "System health"].map((item, i) => <div key={item}><span>{item}</span><div className={`iot-gauge gauge-${i}`}><div>{i === 0 ? <Activity size={25} /> : i === 1 ? <Radio size={25} /> : <Shield size={25} />}</div></div><strong>{i === 0 ? "Monitoring" : i === 1 ? "Connected" : "Operational"}</strong></div>)}</div><div className="iot-chart"><span>Telemetry stream <Circle size={6} fill="#9bd7b8" /></span><MiniChart color="#9bd7b8" /></div></div>;
}

export function ProjectPreview({ variant, large = false }: { variant: Project["preview"]; large?: boolean }) {
  const previews = { reporting: ReportingPreview, business: BusinessPreview, notifications: NotificationPreview, voice: VoicePreview, commerce: CommercePreview, iot: IotPreview };
  const Preview = previews[variant];
  return <div className={`project-preview preview-${variant} ${large ? "preview-large" : ""}`} aria-hidden="true"><div className="preview-grid" /><span className="preview-label">{variant === "voice" ? "HUMAN × TECHNOLOGY" : variant === "notifications" ? "ALWAYS IN SYNC" : variant === "iot" ? "SIGNAL, NOT NOISE" : variant === "commerce" ? "DESIGNED FOR EVERYDAY" : "COMPLEXITY, SIMPLIFIED"}</span><span className="preview-concept">UI CONCEPT <ArrowUpRight size={10} /></span><div className="preview-inner"><Preview /></div><span className="preview-corner">+</span></div>;
}
